---
abstract: 'Basic implementation of the XDG base directory specification'
author:
  - 'Kiyoshi Aman <kiyoshi.aman@gmail.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-XDG
provides:
  File::XDG:
    file: lib/File/XDG.pm
    version: 0.02
requires:
  File::HomeDir: 0
  Path::Class: 0
  perl: v5.12.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
